name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: atul
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up credentials
        # run: |
        #   scp '${{ vars.LIVE_CREDENTIAL_CONFIG }}' /var/www/html/test-cicd/git_creds/credentials.js
        run: |
          
          cat << EOF > /var/www/html/test-cicd/git_creds/credentials.js
          # { db_pass = '${{ vars.db_pass }}',
          #   api_key = '${{ vars.api_key }}',
          #   port = '${{ vars.port }}',
          #   access_key = '${{ vars.access_key }}',
          #   secret_key = '${{ vars.secret_key }}',
          #   username_key = '${{ vars.username_key }}',
          #   password_key = '${{ vars.password_key }}'
              '${{ vars.LIVE_CREDENTIAL_CONFIG }}'
           }
          EOF
          
      - name: remove curly bracket
        run: |
           sed -i 's/{//g; s/}//g' /var/www/html/test-cicd/git_creds/credentials.js

      - name: Copy website files to production server
        run: |
          scp -r index.html /var/www/html/

          # Copy live_credential_config to git_creds directory
          #scp ${ LIVE_CREDENTIAL_CONFIG } /var/www/html/test-cicd/git_creds/credentials.js
          
      - name: Restart NGINX on production server
        run: 'sudo systemctl restart nginx'

