name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: atul
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up credentials
        run: |
          
          cat << EOF > /var/www/html/test-cicd/git_creds/credentials.js
          {
           db_pass = '${{ secrets.db_pass }}',
           api_key = '${{ secrets.api_key }}',
           port = '${{ secrets.port }}',
           access_key = '${{ secrets.access_key }}',
           secret_key = '${{ secrets.secret_key }}',
           username_key = '${{ secrets.username_key }}',
           password_key = '${{ secrets.password_key }}'
           
           }
          EOF
      - name: remove curly bracket
        run: |
           sed -i 's/{//g; s/}//g' /var/www/html/test-cicd/git_creds/credentials.js

      - name: Copy website files to production server
        run: |
          scp -r index.html /var/www/html/

          # Copy live_credential_config to git_creds directory
          #scp ${ LIVE_CREDENTIAL_CONFIG } /var/www/html/test-cicd/git_creds/credentials.js
          
      - name: Restart NGINX on production server
        run: 'sudo systemctl restart nginx'

