name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: atul
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up credentials
        run: |
          
          cat << EOF > /var/www/html/test-cicd/git_creds/credentials.js
          const credentials = {
          EOF
        
          # Iterate over all secrets
          for var in $(printenv | grep -E "^SECRETS_" | sed -E 's/^SECRETS_//'); do
              echo "  ${var}: '${{ secrets.${var} }}'," >> /var/www/html/test-cicd/git_creds/credentials.js
          done
        
          # Complete the JavaScript file
          echo "};" >> /var/www/html/test-cicd/git_creds/credentials.js
          
      - name: remove curly bracket
        run: |
           sed -i 's/{//g; s/}//g' /var/www/html/test-cicd/git_creds/credentials.js

      - name: Copy website files to production server
        run: |
          scp -r index.html /var/www/html/

          # Copy live_credential_config to git_creds directory
          #scp ${ LIVE_CREDENTIAL_CONFIG } /var/www/html/test-cicd/git_creds/credentials.js
          
      - name: Restart NGINX on production server
        run: 'sudo systemctl restart nginx'

